### PR TITLE
Update workflows.rst

### PR DESCRIPTION
**Pull request by bluetyson**
Shiftmap.
Typos to entertain.

### CODE REVIEW

**Comment by brenmous** [comment]
Yes this is hilarious. 
Thanks for fixing these typos.
Could I please ask you make these commits in one branch and submit a single pull request?

**Comment by bluetyson** [comment]
Sure.  Basically I had been doing them ad hoc on the web as I came across them now again.

**Comment by bluetyson** [comment]
Ok that should do it.

**Comment by brenmous** [comment]
Thank you for reading the documentation and providing these fixes. However there are some code changes mixed up in here. I appreciate the contributions but please submit code changes in their own PRs.

**Comment by bluetyson** [comment]
Sure, do you want separate for diffferent things?

**Pull request closed without merging**
